#? USERS

#* Get All users
GET http://localhost:8000/users

###

#* Delete specific user
DELETE http://localhost:8000/users/628bd15d6343efa6ae3878af

###

#? REGISTER
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "username": "anna haralas10",
    "password": "ba",
    "email": "annagmail.com"
}

###

#? LOGIN
POST http://localhost:8000/users/login
Content-Type: application/json

{ "username": "Eleni", "password": "agapi123" }

###

#? CATEGORIES 

#* Get All Categories
GET http://localhost:8000/categories

###

#* Create a Category
POST http://localhost:8000/categories
Content-Type: application/json

{
    "author": "628bd15d6343efa6ae3878af",
    "header": "greek language 2"
}

###

#* Update a category
PATCH http://localhost:8000/categories/6289590c1c7ba225f4f9aaed
Content-Type: application/json

{
    "header": "ellinika"
}

###

#* Delete a category
DELETE http://localhost:8000/categories/628bd1696343efa6ae3878b2

###

///////////////////////// * /////////////////////////


#? FLASHCARDS

#* Get All Flashcards
GET http://localhost:8000/flashcards

###

#* Create a Flashcard
POST http://localhost:8000/flashcards
Content-Type: application/json

{
    "front": "geia sou",
    "back": "hallo",
    "category": "62898f4a1486bead9806e628"
}

###

#* Update a flashcard
PATCH http://localhost:8000/flashcards/62895a2034b6da66f30af7f2
Content-Type: application/json

{
    "front": "dromos",
    "back": "street"
}

###

#* Delete a flashcard
DELETE http://localhost:8000/flashcards/6289700c9ef617f4f9658454
