#? USERS

#* Get All users
GET http://localhost:8000/users

###

#? REGISTER
POST http://localhost:8000/register
Content-Type: application/json

{
    "username": "Eleni",
    "password": "agapi123",
    "email": "eleni@gmail.com"
}

###

#? LOGIN
POST http://localhost:8000/login
Content-Type: application/json

{ "username": "Eleni", "password": "agapi123" }

###

#? CATEGORIES 

#* Get All Categories
GET http://localhost:8000/categories

###

#* Create a Category
POST http://localhost:8000/categories
Content-Type: application/json

{
    "author": "6289734814fe49c837aa8ee2",
    "header": "web development"
}

###

#* Update a category
PATCH http://localhost:8000/categories/6289590c1c7ba225f4f9aaed
Content-Type: application/json

{
    "header": "ellinika"
}

###

#* Delete a category
DELETE http://localhost:8000/categories/6289737314fe49c837aa8ee9

###

///////////////////////// * /////////////////////////


#? FLASHCARDS

#* Get All Flashcards
GET http://localhost:8000/flashcards

###

#* Create a Flashcard
POST http://localhost:8000/flashcards
Content-Type: application/json

{
    "front": "Javascript",
    "back": "Javascript (JS) is a scripting languages, primarily used on the Web.",
    "category": "6289737314fe49c837aa8ee9"
}

###

#* Update a flashcard
PATCH http://localhost:8000/flashcards/62895a2034b6da66f30af7f2
Content-Type: application/json

{
    "front": "dromos",
    "back": "street"
}

###

#* Delete a flashcard
DELETE http://localhost:8000/flashcards/6289700c9ef617f4f9658454
