#? USERS

#* Get All users
GET http://localhost:8000/users

###

#* Delete specific user
DELETE http://localhost:8000/users/628ca3473de8855266ca29cf

###

#? REGISTER
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "username": "eleni",
    "password": "banana12",
    "email": "eleni@gmail.com"
}

###

#? LOGIN
#! Doesnt check password
POST http://localhost:8000/users/login
Content-Type: application/json

{ "email": "eleni@gmail.com", "password": "banana12" }

###

#? CATEGORIES 

#* Get All Categories
GET http://localhost:8000/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhjYWQzMzc5ZGU4YzQ3ZmI5YzNjNWEiLCJpYXQiOjE2NTMzODc1NzYsImV4cCI6MTY1MzQwNTU3Nn0.UYP4rishOgzHA-k3RyrWlyGdw__YLg4pLfkGhDkLEq0

###

#* Create a Category
POST http://localhost:8000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhjYWQzMzc5ZGU4YzQ3ZmI5YzNjNWEiLCJpYXQiOjE2NTMzODc1NzYsImV4cCI6MTY1MzQwNTU3Nn0.UYP4rishOgzHA-k3RyrWlyGdw__YLg4pLfkGhDkLEq0

{   
    "header": "greek"
}

###

#* Update a category
PATCH http://localhost:8000/categories/628bf1e8c893b240a312dbfa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhjYWQzMzc5ZGU4YzQ3ZmI5YzNjNWEiLCJpYXQiOjE2NTMzODc1NzYsImV4cCI6MTY1MzQwNTU3Nn0.UYP4rishOgzHA-k3RyrWlyGdw__YLg4pLfkGhDkLEq0

{
    "header": "german"
}

###

#* Delete a category
DELETE http://localhost:8000/categories/628ca3c63de8855266ca29d7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhjYWQzMzc5ZGU4YzQ3ZmI5YzNjNWEiLCJpYXQiOjE2NTMzODc1NzYsImV4cCI6MTY1MzQwNTU3Nn0.UYP4rishOgzHA-k3RyrWlyGdw__YLg4pLfkGhDkLEq0

###

///////////////////////// * /////////////////////////


#? FLASHCARDS

#* Get All Flashcards
GET http://localhost:8000/flashcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhjYWQzMzc5ZGU4YzQ3ZmI5YzNjNWEiLCJpYXQiOjE2NTMzODc1NzYsImV4cCI6MTY1MzQwNTU3Nn0.UYP4rishOgzHA-k3RyrWlyGdw__YLg4pLfkGhDkLEq0

###

#* Create a Flashcard
POST http://localhost:8000/flashcards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhjYWQzMzc5ZGU4YzQ3ZmI5YzNjNWEiLCJpYXQiOjE2NTMzODc1NzYsImV4cCI6MTY1MzQwNTU3Nn0.UYP4rishOgzHA-k3RyrWlyGdw__YLg4pLfkGhDkLEq0

{
    "front": "geia sou",
    "back": "hallo",
    "category": "628cb38bf6c91acea207b14a"
}

###

#* Update a flashcard 
PATCH http://localhost:8000/flashcards/628cb677460ad7dbaf4c239f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhjYWQzMzc5ZGU4YzQ3ZmI5YzNjNWEiLCJpYXQiOjE2NTMzODc1NzYsImV4cCI6MTY1MzQwNTU3Nn0.UYP4rishOgzHA-k3RyrWlyGdw__YLg4pLfkGhDkLEq0

{
    "front": "dromos",
    "back": "street"
}

###

#* Delete a flashcard
DELETE http://localhost:8000/flashcards/628cb4310a43b9d8d9f2a46b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhjYWQzMzc5ZGU4YzQ3ZmI5YzNjNWEiLCJpYXQiOjE2NTMzODc1NzYsImV4cCI6MTY1MzQwNTU3Nn0.UYP4rishOgzHA-k3RyrWlyGdw__YLg4pLfkGhDkLEq0
